USE electronics_retail;

-- Purpose: Create a stored procedure to return total quantity sold and revenue for a given product
-- Logic:
-- The procedure accepts a product ID as input (param_product_id).
-- SUM(oi.quantity) calculates the total units sold for that product.
-- SUM(oi.unit_price * oi.quantity) calculates the total revenue generated by that product.
-- Filtering with WHERE ensures only the specified product is included.
-- CALL statements demonstrate executing the procedure for products with IDs 1 and 2.
DROP PROCEDURE IF EXISTS get_total_sold_and_revenue ;

DELIMITER //

CREATE PROCEDURE get_total_sold_and_revenue (IN param_product_id int)
BEGIN
  SELECT
    oi.product_id,
    SUM(oi.quantity) AS total_quantity_sold,
    SUM(oi.unit_price * oi.quantity) AS total_revenue
  FROM order_items oi
  WHERE oi.product_id = param_product_id;
END //

DELIMITER ;

CALL get_total_sold_and_revenue(1);

CALL get_total_sold_and_revenue(2);
